<Project>
  <PropertyGroup>
    <LangVersion>10.0</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <Version>1.4.1</Version>
    <AssemblyVersion>1.4.1.0</AssemblyVersion>
    <FileVersion>1.4.1.0</FileVersion>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
</Project>
